import { Category, type Word } from '@src/utils/types';

export const animals: Array<Word> = [
  {
    spelling: 'лошадь',
    soundsLike: '**LO**SHED',
    meaning: ['horse'],
    pluralForeignKey: 'лошади',
    points: 0,
    categories: [Category.Animals],
  },
  {
    spelling: 'лошади',
    soundsLike: '**LO**SHEDI',
    meaning: ['horses'],
    singularForeignKey: 'лошадь',
    points: 0,
    categories: [Category.Animals],
  },
  {
    spelling: 'кошка',
    soundsLike: '**KO**SHKA',
    meaning: ['cat'],
    pluralForeignKey: 'кошки',
    points: 0,
    categories: [Category.Animals],
  },
  {
    spelling: 'кошки',
    soundsLike: '**KO**SHKI',
    meaning: ['cats'],
    singularForeignKey: 'кошка',
    points: 0,
    categories: [Category.Animals],
  },
  {
    spelling: 'собака',
    soundsLike: 'SA**BA**KA',
    meaning: ['dog'],
    // pluralForeignKey: '',
    points: 0,
    categories: [Category.Animals],
  },
  {
    spelling: 'орёл',
    soundsLike: 'AR**YOL**',
    meaning: ['eagle'],
    // pluralForeignKey: '',
    points: 0,
    categories: [Category.Animals],
  },
  {
    spelling: 'корова',
    soundsLike: 'KA**RO**VA',
    meaning: ['cow'],
    points: 0,
    categories: [Category.Animals],
    pluralForeignKey: 'коровы',
  },
  {
    spelling: 'коровы',
    soundsLike: 'KA**RO**VUI',
    meaning: ['cows'],
    points: 0,
    categories: [Category.Animals],
    singularForeignKey: 'корова',
  },
  {
    spelling: 'мышка',
    soundsLike: '**MUI**SHKA',
    meaning: ['mouse'],
    points: 0,
    categories: [Category.Animals],
    pluralForeignKey: 'мышки',
  },
  {
    spelling: 'мышки',
    soundsLike: '**MUI**SHKI',
    meaning: ['mice'],
    points: 0,
    categories: [Category.Animals],
    singularForeignKey: 'мышка',
  },
  {
    spelling: 'медведь',
    soundsLike: 'MYED**VYED**',
    meaning: ['bear'],
    points: 0,
    categories: [Category.Animals],
    pluralForeignKey: 'медведи',
  },
  {
    spelling: 'медведи',
    soundsLike: 'MYED**VYE**DI',
    meaning: ['bears'],
    points: 0,
    categories: [Category.Animals],
    singularForeignKey: 'медведь',
  },
  {
    spelling: 'кит',
    soundsLike: 'KIT',
    meaning: ['whale'],
    points: 0,
    categories: [Category.Animals],
    pluralForeignKey: 'киты',
  },
  {
    spelling: 'киты',
    soundsLike: 'KIT',
    meaning: ['whales'],
    points: 0,
    categories: [Category.Animals],
    singularForeignKey: 'кит',
  },
];
