import { Category, type Word } from '@src/utils/types';

export const greetings: Array<Word> = [
  {
    spelling: 'привет',
    soundsLike: '**PRI**VYET',
    meaning: ['hi', 'hello'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'здравствуйте',
    soundsLike: '**ZDRAS**VUITI',
    meaning: ['hello'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'добро пожаловать',
    soundsLike: 'DAB**RO** PA**ZHA**LOVET',
    meaning: ['welcome'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'доброе утра',
    soundsLike: 'DOBREY UTRA',
    meaning: ['good morning'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'добрый день',
    soundsLike: 'DOBREY DYEN',
    meaning: ['good afternoon'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'добрый вечер',
    soundsLike: 'DOBREY VYECHER',
    meaning: ['good evening'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'спокойной ночи',
    soundsLike: 'SPAKOINI NOCHI',
    meaning: ['good night'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'пока',
    soundsLike: 'PA**KA**',
    meaning: ['bye'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'до свидания',
    soundsLike: 'DA SVIDANIYA',
    meaning: ['goodbye'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'до завтра',
    soundsLike: 'DA ZAVTRA',
    meaning: ['see you tomorrow'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'увидимся',
    soundsLike: 'UVIDIMSYA',
    meaning: ['see you later'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'как дела',
    soundsLike: 'KAK DYELA',
    meaning: ['how are you?'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'как поживаете',
    soundsLike: 'KAK PAZIVAYETYE',
    meaning: ['how are you doing?'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'что нового',
    soundsLike: 'SHTO NOVAVA',
    meaning: ["What's new?"],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'ничего нового',
    soundsLike: 'NICHEVO NOVAVA',
    meaning: ['nothing new'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'всё нормально',
    soundsLike: 'VSO NOR**MAL**NA',
    meaning: ["everything's fine"],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'как жизнь',
    soundsLike: 'KAK ZHIZN',
    meaning: ["how's life?"],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'так себе',
    soundsLike: 'KAK SYEBYE',
    meaning: ['so so'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'спасибо',
    soundsLike: 'SPA**SI**BA',
    meaning: ['thank you'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'большое спасибо',
    soundsLike: 'BAL**SHO**YE SPA**SI**BA',
    meaning: ['thank you very much'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'пожалуйста',
    soundsLike: 'PA**ZHA**LUISTA',
    meaning: ['please'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'не за что',
    soundsLike: 'NYA ZA SHTO',
    meaning: ['my pleasure', "you're welcome"],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'хорошо',
    soundsLike: 'HARA**SHO**',
    meaning: ['fine', 'ok'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'хорошего дня',
    soundsLike: 'HA**RO**SHEVO DEN**YA**',
    meaning: ['Have a good day'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'хорошего вечера',
    soundsLike: 'HA**RO**SHEVO V**YE**CHYERA',
    meaning: ['Have a good evening'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'хороших выходных',
    soundsLike: 'HA**RO**SHIKH VI**KHA*DNIKH',
    meaning: ['Have a nice weekend'],
    points: 0,
    categories: [Category.Greetings],
  },
  {
    spelling: 'извините',
    soundsLike: 'IZVI**NI**TY',
    meaning: ['excuse me', 'sorry'],
    points: 0,
    categories: [Category.Greetings],
  },
];
