import { Category, type Word } from '@src/utils/types';

export const other: Array<Word> = [
  {
    spelling: 'друг',
    soundsLike: 'DROOG',
    meaning: ['friend'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'здесь',
    soundsLike: 'ZDIS',
    meaning: ['here'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'там',
    soundsLike: 'TAM',
    meaning: ['there'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'это',
    soundsLike: 'ETA', // ETAT ETI
    meaning: ['this'],
    // metadata: ['етот', 'эти']
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'тарелка',
    soundsLike: 'TAREILKA',
    meaning: ['plate'],
    pluralForeignKey: 'тарелки',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'тарелки',
    soundsLike: 'TAREILKI',
    meaning: ['plates'],
    singularForeignKey: 'тарелка',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'мальчик',
    soundsLike: '**MAL**CHIK',
    meaning: ['boy'],
    pluralForeignKey: 'мальчики',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'мальчики',
    soundsLike: '**MAL**CHIKI',
    meaning: ['boys'],
    singularForeignKey: 'мальчик',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'девочка',
    soundsLike: '**DYE**VOCHKA',
    meaning: ['girl'],
    pluralForeignKey: 'девочки',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'девочки',
    soundsLike: '**DYE**VOCHKI',
    meaning: ['girls'],
    singularForeignKey: 'девочка',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'дети',
    soundsLike: '**DEY**TI',
    meaning: ['children'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'мужчина',
    soundsLike: "MUI**ZHCH'I**NA",
    meaning: ['man'],
    pluralForeignKey: 'мужчины',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'мужчины',
    soundsLike: 'MUZH**CHI**NI',
    meaning: ['men'],
    singularForeignKey: 'мужчина',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'женщина',
    soundsLike: '**ZHEN**SHINA',
    meaning: ['woman'],
    pluralForeignKey: 'женщины',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'женщины',
    soundsLike: '**ZHEN**SHINIE',
    meaning: ['women'],
    singularForeignKey: 'женщина',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'дом',
    soundsLike: 'DOM',
    meaning: ['house'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'офис',
    soundsLike: '**O**FIS',
    meaning: ['office'],
    pluralForeignKey: 'офисы',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'офисы',
    soundsLike: '**O**FISI',
    meaning: ['offices'],
    singularForeignKey: 'офис',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'метро',
    soundsLike: 'MET**RO**',
    meaning: ['subway'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'человек',
    soundsLike: 'CHELA**VEK**',
    meaning: ['person'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'озеро',
    soundsLike: '**O**ZIRA',
    meaning: ['lake'],
    pluralForeignKey: 'озёра',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'озёра',
    soundsLike: 'AZ**YO**RA',
    meaning: ['lakes'],
    singularForeignKey: 'озеро',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'тетрадь',
    soundsLike: 'TET**RAD**',
    meaning: ['notebook'],
    pluralForeignKey: 'тетради',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'тетради',
    soundsLike: 'TET**RA**DI',
    meaning: ['notebooks'],
    singularForeignKey: 'тетрадь',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'стол',
    soundsLike: 'STOL',
    meaning: ['table'],
    pluralForeignKey: 'столы',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'столы',
    soundsLike: 'STA**LUI**',
    meaning: ['tables'],
    singularForeignKey: 'стол',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'полотенце',
    soundsLike: 'PALA**TIEN**TSYE',
    meaning: ['towel'],
    pluralForeignKey: 'полотенца',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'полотенца',
    soundsLike: 'PALA**TIEN**TSA',
    meaning: ['towels'],
    singularForeignKey: 'полотенце',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'телефон',
    soundsLike: 'TYELEPHON',
    meaning: ['phone'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'такси',
    soundsLike: 'TAKSI',
    meaning: ['taxi'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'план',
    soundsLike: 'PLAN',
    meaning: ['plan'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'ребёнок',
    soundsLike: 'REB**YO**NAK',
    meaning: ['child', 'baby'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'велосипед',
    soundsLike: 'VELOSIP**YED**',
    meaning: ['bicycle'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'ну',
    soundsLike: 'NU',
    meaning: ['well'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'всё',
    soundsLike: 'VSO',
    meaning: ['everything', 'all', 'anything'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'уже',
    soundsLike: 'UZHE',
    meaning: ['already'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'конечно',
    soundsLike: 'KANI**YECH**NA',
    meaning: ['of course'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'утро',
    soundsLike: 'UTRA',
    meaning: ['morning'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'кафе',
    soundsLike: 'KAFE',
    meaning: ['cafe'],

    points: 0,
    categories: [Category.Other],
  },

  {
    spelling: 'парк',
    soundsLike: 'PARK',
    meaning: ['park'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'добрый',
    soundsLike: 'DOBREY',
    meaning: ['good', 'kind', 'nice'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'дела',
    soundsLike: 'DYELA',
    meaning: ['matter', 'business', 'case'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'день',
    soundsLike: 'DYЕN',
    meaning: ['day'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'вечер',
    soundsLike: '**VYE**CHER',
    meaning: ['evening'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'город',
    soundsLike: '**GO**RAD',
    meaning: ['city'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'свитер',
    soundsLike: '**SVI**TER',
    meaning: ['Sweater'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'или',
    soundsLike: '**I**LI',
    meaning: ['or'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'рюкзак',
    soundsLike: '**RIU**KZAK',
    meaning: ['backpack'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'да',
    soundsLike: 'DA',
    meaning: ['yes'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'нет',
    soundsLike: 'NYET',
    meaning: ['no'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'меню',
    soundsLike: 'MENU',
    meaning: ['menu'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'сон',
    soundsLike: 'SON',
    meaning: ['dream'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'маленький',
    soundsLike: 'MALYENKI',
    meaning: ['small'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'жаль',
    soundsLike: 'ZHAL',
    meaning: ['what a pity', 'it is a pitty', 'sorry'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'йога',
    soundsLike: 'YOGA',
    meaning: ['yoga'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'шорты',
    soundsLike: 'SHORTI',
    meaning: ['shorts'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'кровать',
    soundsLike: 'KRA**VAT**',
    meaning: ['bed'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'тоже',
    soundsLike: '**TO**ZHE',
    meaning: ['also', 'too'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'туалет',
    soundsLike: '**TU**ALET',
    meaning: ['toilet', 'bathroom'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'камень',
    soundsLike: '**KA**MYEN',
    meaning: ['stone'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'дверь',
    soundsLike: 'DVYER',
    meaning: ['door'],
    pluralForeignKey: 'двери',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'двери',
    soundsLike: 'DVIRI',
    meaning: ['doors'],
    singularForeignKey: 'дверь',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'карандаш',
    soundsLike: 'KARAN**DASH**',
    meaning: ['pencil'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'дерево',
    soundsLike: 'DYEREVA',
    meaning: ['tree'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'далеко',
    soundsLike: 'DALIE**KO**',
    meaning: ['far away'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'площадь',
    soundsLike: '**PLO**SHID',
    meaning: ['square (place)'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'на',
    soundsLike: 'NA',
    meaning: ['on', 'is on', 'there is...on'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'страшно',
    soundsLike: '**STRASH**NA',
    meaning: ['scary'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'акно',
    soundsLike: 'AK**NO**',
    meaning: ['window'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'стул',
    soundsLike: 'STOOL',
    meaning: ['chair'],
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'школа',
    soundsLike: '**SHKO**LI',
    meaning: ['school'],
    pluralForeignKey: 'школы',
    points: 0,
    categories: [Category.Other],
  },
  {
    spelling: 'школы',
    soundsLike: '**SHKO**LA',
    meaning: ['schools'],
    singularForeignKey: 'школа',
    points: 0,
    categories: [Category.Other],
  },
  // {
  //   spelling: '',
  //   soundsLike: '',
  //   meaning: [''],
  //   pluralForeignKey: '',
  //   singularForeignKey: '',
  //   points: 0,
  //   categories: [Category.Other],
  // },
];
