import { Category, type Word } from '@src/utils/types';

export const questions: Array<Word> = [
  {
    spelling: 'где',
    soundsLike: 'GDE',
    meaning: ['where'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'кто',
    soundsLike: 'KTO',
    meaning: ['who'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'что',
    soundsLike: 'SHTO',
    meaning: ['what'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'когда',
    soundsLike: 'KAGDA',
    meaning: ['when'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'какой',
    soundsLike: 'KAKOI',
    meaning: ['which (question)'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'почему',
    soundsLike: 'PACHYEMU',
    meaning: ['why'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'сколько',
    soundsLike: '**SKO**LKA',
    meaning: ['how much'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'как',
    soundsLike: 'KAK',
    meaning: ['how'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'куда',
    soundsLike: 'KU**DA**',
    meaning: ['to where'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  {
    spelling: 'откуда',
    soundsLike: 'ATKU**DA**',
    meaning: ['from where'],
    points: 0,
    categories: [Category.QuestionWord],
  },
  // {
  //   spelling: 'как',
  //   soundsLike: 'KAK',
  //   meaning: ['how'],
  //   points: 0,
  //   categories: [Category.QuestionWord],
  // },
];
